#!/usr/bin/with-contenv bash

# If DEBUG is set, show all commands being executed AND fail fast if one of the commands
# raises an exception
if [[ -n $DEBUG_DIGGER ]] ; then
    set -ex
fi

export PRIMARY_IP=$(dig @resolver4.opendns.com myip.opendns.com +short -4)

temp_file=$(mktemp)
url=${URL/https:\/\//} # strip protocol from url
if [[ -z $DISABLE_DIGGER ]] ; then
    while true ; do
        dig $url > $temp_file
        DIG_RESULT=`cat $temp_file`

        # matching:
        # `;; ANSWER SECTION:
        # google.com.		192	IN	A	142.250.191.78`
        ANSWER_SECTION=`echo $DIG_RESULT | grep -o 'ANSWER SECTION: \w.* ;; '`

        # matching:
        # `A	142.250.191.78`, extracting only `142.250.191.78`
        RESPONSE_IP=`echo $ANSWER_SECTION \
            | grep -o 'A [[:digit:]]*\.[[:digit:]]*\.[[:digit:]]*\.[[:digit:]]*' \
            | sed 's/A//g' \
            | sed 's/\s//g'`

        # matching:
        # `google.com.		192	IN	A	142.250.191.78`, extracting only `google.com.`
        ANSWER_ADDRESS=`echo $ANSWER_SECTION \
            | grep -o -E '([^\ ]+)\ [[:digit:]]* IN A' \
            | sed 's/ IN A//g' \
            | sed 's/ [0-9]*//g'`

        # matching:
        # `Query time: 25 msec`, extracting only the digits
        QUERY_TIME=`echo $DIG_RESULT \
            | grep -o 'Query time: [[:digit:]]*' \
            | sed -e 's/Query time://g' \
            | sed 's/\s//g'`

        # matching:
        # `SERVER: 172.16.3.13#53(172.16.3.13)`, extracting only `172.16.3.13`
        DNS_SERVER=`echo $DIG_RESULT \
            | grep -o 'SERVER: [[:digit:]]*\.[[:digit:]]*\.[[:digit:]]*\.[[:digit:]]*' \
            | sed 's/SERVER://g' \
            | sed 's/\s//g'`

        echo "{\"eventType\":\"DiagnosticsDig\", \"dns_server_ip\":\"$DNS_SERVER\", \"response_ip\":\"$RESPONSE_IP\", \"query_time_ms\":$QUERY_TIME, \"response_name\":\"$ANSWER_ADDRESS\", \"hostname\":\"$OUTER_HOSTNAME\", \"primary_ip\": \"$PRIMARY_IP\" }" > $temp_file

        gzip -c $temp_file | curl -X POST -H "Content-Type: application/json" -H "X-Insert-Key: $EVENTS_INSERT_API_KEY" -H "Content-Encoding: gzip" $COLLECTOR_URL/v1/accounts/$ACCOUNT_ID/events -s -o /dev/null --data-binary @-

        sleep 1
    done
fi
